initial-admin:
  email: firstadmin@space.com
  password: firstpassword123

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/space
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서 스키마 자동 생성/업데이트. 운영 환경에는 none, validate 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # 실행되는 SQL 로그 표시(선택)

logging:
  level:
    org.springframework.security: DEBUG
